# program that takes student names and majors from the user
# and returns either the number of each major or the major of a specific person

import collections
import matplotlib.pyplot as plt

# empty list and dictionary
majorList = []
nameMajorDict = {}

# function that takes dictionary generated by user input and graphs the amount of 
# individuals in each major
def majorGraph(d):
    majors = list(d.keys())
    amount = list(d.values())

    plt.bar(range(len(d)), amount, tick_label=majors)
    plt.show()

# take name and major data from user
name = input("Enter the student name (Enter 'stop' when done): ")
while name!= "stop":
    major = input("Enter the student's major: ")
    majorList.append(major)
    nameMajorDict[name] = major
    name = input("Enter the student name (Enter 'stop' when done): ")

# return major of a student or number of studejnts in each major
responseQ1 = input("Would you like to search for the major of a student (yes/no)?:  ")
if responseQ1 == "yes":
    nameInput = input("Enter the student name: ")
    print("Their major is " + nameMajorDict[nameInput])
if responseQ1 == "no":
    responseQ2 = input("Would you like to find out the number of students in each major (yes/no)?: ")
    if responseQ2 == "yes":
        majorCount = (collections.Counter(majorList))
        print(majorCount)
        majorGraph(majorCount)
    if responseQ2 == "no":
        print("okay, bye bye!")
        quit()